# COVID-19 Tests

Jimuel Celeste, Jr. 

Objective: To estimate the availability of tests in provinces through the number of tests per province.

In [87]:
import pandas as pd

## COVID-19 Testing Facilities

In [88]:
facilities = "/Users/jimuelcelestejr/Documents/codebook/covid-asmr-philippines/data/COVID-19 Tests/COVID testing facilities (1).xlsx"
facilities = pd.read_excel(facilities)

In [89]:
facilities

,ID,REGION,PROVINCE,EDITED FACILITY NAME,FACILITY,TYPE,TEST,Remarks
0,1.0,NCR,Metro Manila,a star laboratories,"A Star Laboratories, Inc",Private,rRT PCR,NaN
1,2.0,NCR,Metro Manila,NaN,AC Molecular Diagnostic Laboratory,Private,rRT PCR,NaN
2,3.0,CARAGA,Surigao del Sur,NaN,Adela Serra TY Memorial Medical Center,Government,rRT PCR,NaN
3,4.0,NCR,Metro Manila,NaN,Al Molecular Diagnostic Laboratory,Private,rRT PCR,NaN
4,5.0,NCR,Metro Manila,al molecular diagnostic laboratory - genexpert,Al Molecular Diagnostic Laboratory,Private,Cartridge - Based PCR,NaN
...,...,...,...,...,...,...,...,...
391,348.0,R9,Zamboanga del Sur,zamboanga city medical center genexpert labora...,Zamboanga City Medical Center - NTP Culture La...,Government,Cartridge - Based PCR,NaN
392,NaN,R9,Zamboanga del Sur,zamboanga city medical center (plate-based),NaN,NaN,NaN,NaN
393,NaN,R9,Zamboanga del Sur,zamboanga city medical center - da satellite l...,NaN,NaN,NaN,NaN
394,349.0,R9,Zamboanga del Norte,NaN,Zamboanga del Norte Medical Center,Government,rRT PCR,NaN
395,350.0,R9,Zamboanga del Sur,zamboanga del sur medical center pcr laboratory,Zamboanga del Sur Medical Center,Government,rRT PCR,NaN

In [90]:
tests = "/Users/jimuelcelestejr/Documents/codebook/covid-asmr-philippines/data/COVID-19 Tests/DOH COVID Data Drop_ 20240103 - 07 Testing Aggregates.csv"
tests = pd.read_csv(tests)

/var/folders/ny/jv8cwgpx7ng41dfgnqsvzdnw0000gn/T/ipykernel_23663/2228410702.py:2: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  tests = pd.read_csv(tests)

In [91]:
tests

,facility_name,report_date,avg_turnaround_time,daily_output_samples_tested,daily_output_unique_individuals,daily_output_positive_individuals,daily_output_negative_individuals,daily_output_equivocal,daily_output_invalid,remaining_available_tests,backlogs,cumulative_samples_tested,cumulative_unique_individuals,cumulative_positive_individuals,cumulative_negative_individuals,pct_positive_cumulative,pct_negative_cumulative,validation_status
0,A Star Laboratories,2020-12-08,24.0,15.0,15.0,1.0,14.0,0.0,0.0,8.0,0.0,15,15,1,14,0.07,0.93,NaN
1,A Star Laboratories,2020-12-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
2,A Star Laboratories,2020-12-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
3,A Star Laboratories,2020-12-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
4,A Star Laboratories,2020-12-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393640,truhealthencoder@gmail.com,2023-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393641,truhealthencoder@gmail.com,2023-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393642,truhealthencoder@gmail.com,2023-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393643,truhealthencoder@gmail.com,2023-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393644,truhealthencoder@gmail.com,2024-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN

In [92]:
first_list = [facility.lower() for facility in tests['facility_name'].unique()]
first_list

['a star laboratories',
 'ac molecular diagnostic laboratory',
 'al molecular diagnostic laboratory',
 'al molecular diagnostic laboratory - genexpert',
 'apex mining co. inc.',
 'adela serra ty memorial medical center',
 'allegiant regional care hospital',
 'allegiant regional care hospital - cartridge based',
 'allied care expert - valenzuela',
 'allied medical and molecular laboratory corp.',
 'amai pakpak medical center genexpert laboratory',
 'amai pakpak medical center molecular laboratory',
 'amang rodriguez memoral medical center (rt pcr)',
 'amang rodriguez memorial center genexpert laboratory',
 "amosup seamen's hospital",
 'antipolo city molecular laboratory',
 'antique bio-molecular laboratory',
 'army general hospital molecular laboratory',
 'asian hospital and medical center',
 'asian hospital and medical center - cartridge',
 'asian hospital and medical center - rt-pcr',
 'ateneo molecular pathology laboratory',
 'brtth covid-19 testing laboratoy',
 'bacolod queen of mercy hospital',
 'baguio general hospital and medical center',
 'bataan general hospital (rt pcr)',
 'bataan general hospital and medical center genexpert laboratory',
 'batangas medical center genexpert laboratory',
 'batangas medical center rt pcr laboratory',
 'be safe md, inc.',
 'be safe md, inc. - cartridge based',
 'benguet general hospital',
 'best diagnostic corporation',
 'bicol medical center genexpert laboratory',
 'bicol medical center rt-pcr laboratory',
 'bicol region general hospital and geriatric medical center',
 'bicol regional diagnostic and reference laboratory (brdrl)',
 'biopath clinical diagnostic, inc.',
 'biopath clinical diagnostics, inc - cebu',
 'biopath clinical diagnostics, inc - cebu genexpert laboratory',
 'biopath clinical diagnostics, inc. (e. rodriguez)',
 'biopath clinical diagnostics, inc. (e. rodriguez) genexpert laboratory',
 'biopath clinical diagnostics, inc. - afrims',
 'biopath clinical diagnostics, inc. genexpert laboratory',
 'biopath clinical diagnostics, inc. - afrims genexpert laboratory',
 'bohol containerized pcr laboratory',
 'breeze medical services',
 'brokenshire integrated health ministries, inc.',
 'bukidnon provincial medical center',
 'bulacan medical center (rt pcr)',
 'bulacan medical center genexpert laboratory',
 'bureau of quarantine - cartridge-based pcr',
 'butuan medical center (rt pcr)',
 'butuan medical center genexpert laboratory',
 'cabanatuan city m.v. gallego general hospital',
 'cagayan valley chd genexpert laboratory',
 'cagayan valley medical center molecular laboratory',
 'cagayan valley medical center molecular laboratory - cartridge-based',
 'calamba doctors hospital',
 'calamba medical center',
 'caloocan city north medical center',
 'camiguin general hospital - covid-19 molecular laboratory',
 'camsur diagnostic laboratory',
 'caraga regional hospital genexpert laboratory',
 'cardinal santos medical center',
 'cardinal santos medical center cartridge-based pcr',
 'castro maternity hospital and medical center, inc.',
 'cebu doctors university hospital, inc.',
 'cebu doctors university hospital, inc. cartridge-based pcr',
 'cebu tb reference laboratory - genexpert',
 'cebu tb reference laboratory - molecular facility for covid-19 testing',
 "central luzon doctor's hospital genexpert laboratory",
 'century pinnacle diagnostic and medical corporation',
 'chinese general hospital',
 'chinese general hospital - genexpert laboratory',
 'chong hua hospital',
 'chong hua hospital cartridge-based pcr laboratory',
 'city government of zamboanga molecular testing center',
 'city of dasmarinas molecular diagnostic laboratory',
 'ciudad medical zamboanga',
 'community general hospital of san pablo city, inc.',
 'corazon locsin montelibano memorial regional hospital',
 'cotabato regional and medical center genexpert laboratory',
 'cotabato regional and medical center rt pcr',
 'culion sanitarium and general hospital genexpert laboratory',
 'dagupan doctors villaflor memorial hospital',
 'dagupan doctors villaflor memorial hospital - cartridge based',
 'daniel o. mercado medical center',
 'datu halun sakilan memorial hospital (cartridge-based)',
 'davao doctors hospital cartridge - based pcr',
 'davao international airport laboratory',
 'davao one world diagnostic center incorporated',
 'davao regional medical center genexpert laboratory',
 'davao regional medical center rt pcr',
 'davao de oro provincial hospital',
 'de la salle medical and health sciences institute',
 'de los santos medical center',
 'democrito o. plaza memorial hospital',
 'detoxicare molecular diagnostics laboratory',
 'detoxicare molecular diagnostics laboratory (1)',
 'detoxicare molecular diagnostics laboratory (2)',
 'detoxicare molecular diagnostics laboratory - cartridge-based pcr',
 'divine word hospital',
 'dr. arturo pingoy medical center genexpert laboratory',
 'dr. jorge p. royeca hospital',
 'dr. jose fabella memorial hospital - cartridge-based pcr',
 'dr. jose fabella memorial hospital - rt pcr',
 'dr. jose n. rodriguez memorial hospital and sanitarium (tala) genexpert laboratory',
 'dr. jose n. rodriguez memorial hospital and sanitarium (tala) rt pcr',
 'dr. jose rizal memorial hospital',
 'dr. pablo o. torre memorial hospital',
 'dr. paulino j. garcia memorial research and medical center',
 'dr. rafael s. tumbokon memorial hospital',
 'east avenue medical center',
 'east avenue medical center - cartridge based',
 'eastern visayas regional covid testing center',
 'el roi molecular diagnostic laboratory',
 'el roi molecular diagnostic laboratory (cartridge-based pcr)',
 'ermita molecular diagnostic laboratory, inc.',
 'excellab diagnostic center',
 'f.y manalo medical foundation, inc. (formerly new era hospital)',
 'fatima university medical center antipolo corp.',
 'fe del mundo medical center',
 'first aide diagnostic center',
 'first cabuyao hospital and medical center, inc.',
 'firstchoice diagnostics inc.',
 'gentrimed cartridge-based pcr laboratory',
 'gentrimed molecular laboratory',
 'governor celestino gallares memorial medical center',
 'graman medical & maternity hospital inc molecular laboratory - cartridge based',
 'graman medical & maternity hospital molecular laboratory',
 'greencity medical center',
 'gregorio t. lluch memorial hospital',
 'health connect diagnostics and clinics inc.',
 'health delivery systems',
 'health metrics',
 'healthway medical',
 'heartland medical and diagnostic center',
 'hero laboratories',
 'hi-precision diagnostics (qc)',
 'hi-precision diagnostics cartridge-based pcr laboratory (qc)',
 'iom - manila health centre laboratory - genexpert',
 'ilocos sur provincial hospital gabriela silang',
 'ilocos training regional medical center genexpert laboratory',
 'ilocos training and regional medical center',
 'iloilo mission hospital molecular biology laboratory',
 'iloilo provincial hospital',
 'interpharma solutions philippines, inc.',
 'intramuros molecular laboratory',
 'jt cenica medical health system',
 'jtrbicol molecular diagnostic laboratory',
 'jose b. lingad memorial general hospital',
 'jose b. lingad memorial general hospital - genexpert laboratory',
 'jose r. reyes memorial medical center genexpert laboratory',
 'kairos diagnostics laboratory',
 'kairos diagnostics laboratory cartridge-based pcr',
 'kairos diagnostics laboratory rt-pcr (1)',
 'kairos diagnostics laboratory rt-pcr (2)',
 'kaiser medical center inc.',
 'kidapawan city molecular laboratory',
 'laguna holy family hospital, inc.',
 'laguna holy family hospital, inc. - satellite molecular laboratory',
 'lanao del norte covid-19 testing laboratory',
 'las pinas general hospital and satellite trauma center',
 'las pinas general hospital and satellite trauma center genexpert laboratory',
 'lifecore biointegrative inc.',
 'lipa medix medical center - cartridge-based pcr',
 'lorma medical center',
 'lorma medical center - cartridge based',
 'los amigos davao laboratory',
 'lucena united doctors hospital and medical center',
 'luis hora memorial regional hospital',
 'lung center of the philippines (lcp)',
 'lung center of the philippines genexpert laboratory',
 'm diagnostics philippines, inc.',
 'm diagnostics philippines, inc. - pasay (cartridge)',
 'm diagnostics philippines, inc. - pasay (rt-pcr)',
 'mabini community hospital cartridge-based pcr laboratory',
 'maguindanao provincial hospital',
 'maguindanao provincial hospital - cartridge based',
 'maguindanao provincial hospital - rt-pcr',
 'makati life medical center',
 'makati medical center (mmc)',
 'manila diagnostic center for ofw inc.',
 'manila doctors hospital',
 'manila doctors hospital - cartridge-based',
 'manila doctors hospital - rt-pcr',
 'manila healthtek inc.',
 'manuel j. santos hospital',
 'maria estrella general hospital',
 'maria reyna xavier university hospital inc.',
 'mariano marcos memorial hospital (rt pcr)',
 'mariano marcos memorial hospital genexpert laboratory',
 'marikina molecular diagnostics laboratory (mmdl)',
 'marikina valley medical center',
 'marilao medical and diagnosc clinic, inc. - pasay city',
 'marilao medical and diagnostic clinc, inc.',
 'marilao medical and diagnostic clinic, inc. - dagupan city',
 'marinduque provincial hospital',
 'mariveles district hospital',
 'mariveles district hospital genexpert laboratory',
 'mary mediatrix medical center',
 'mauban municipal health office molecular laboratory',
 'mayor hilarion a. ramiro sr. medical center',
 'mayor hilarion a. ramiro sr. medical center - cartridge based',
 'medical center manila, inc.',
 'medical center paraÃ±aque, inc.',
 'medical center of paranaque, inc. - cartriged based',
 'medical center of taguig city, inc.',
 'metro health specialist hospital',
 'metro iloilo hospital and medical center',
 'metro north medical center and hospital inc.',
 'metro pangasinan molecular laboratory',
 'misamis occidental rt-pcr laboratory',
 'mlang district hospital',
 'mother teresa of calcutta medical center',
 'mother teresa of calcutta medical center cartridge-based',
 'mount carmel diocesan general hospital',
 'multi-lifecare foundation molecular laboratory',
 'naga city hospital molecular laboratory',
 "national children's hospital (cartridge-based pcr)",
 'national kidney and transplant institute',
 'national kidney and transplant institute genexpert laboratory',
 'negros oriental provincial hospital',
 'new world diagnostic premium medical branch',
 'new world diagnostic premium medical branch - genexpert laboratory',
 'next gen pcr diagnostic laboratory',
 'next gen pcr diagnostic laboratory - cartridge-based pcr',
 'next gen pcr diagnostic laboratory - cebu',
 'next gen pcr diagnostic laboratory - nueva ecija',
 'northern mindanao medical center genexpert laboratory',
 'northern mindanao medical center rt-pcr laboratory',
 'northern mindanao tb regional center',
 'notre dame de chartres hospital',
 "ospa - farmers' medical center",
 'occidental mindoro provincial hospital genexpert laboratory',
 'olayn medical laboratory, inc.',
 'olayn medical laboratory, inc. - genexpert laboratory',
 'olongapo city molecular diagnostic laboratory',
 'oriental mindoro provincial hospital - rtpcr',
 'oriental mindoro provincial hospital genexpert laboratory',
 'ospital ng imus',
 'ospital ng lipa',
 'ospital ng muntinlupa',
 'ospital ng palawan genexpert laboratory',
 'ospital ng paraÃ±aque district ii',
 'our lady of mt. carmel medical center molecular laboratory',
 'pcr med molecular laboratory',
 'pho - molecular biology laboratory',
 'pnp crime laboratory',
 'pnp general hospital',
 'prc - negros occidental molecular laboratory',
 'prc- batangas chapter molecular laboratory',
 'pro 11 rt-pcr molecular laboratory',
 'psg station hospital molecular laboratory',
 'pampanga medical specialist hospital - cartridge-based pcr',
 'pampanga molecular laboratory',
 'pampanga premier medical center',
 'pangasinan molecular diagnostic laboratory',
 'parkway medical and diagnostic center',
 'pasig city molecular laboratory',
 'pasig doctors medical center, inc.',
 'perpetual succour hospital of cebu, inc.',
 'perpetual succour hospital of cebu, inc. - genexpert laboratory',
 'philippine airport diagnostic laboratory',
 'philippine airport diagnostic laboratory (cartridge-based pcr)',
 "philippine children's medical center",
 'philippine general hospital genexpert laboratory',
 'philippine heart center genexpert laboratory',
 'philippine medical diagnostic & laboratory center corporation',
 'philippine red cross (prc)',
 'philippine red cross - cagayan de oro chapter',
 'philippine red cross - cebu chapter',
 'philippine red cross - logistics and training center',
 'philippine red cross - molecular biology laboratory',
 'philippine red cross - port area',
 'philippine red cross - port area - cartridge based',
 'philippine red cross - port area rt-pcr',
 'philippine red cross - surigao del norte molecular laboratory',
 'philippine red cross clark molecular laboratory',
 'philippine red cross cotabato city - maguindanao molecular laboratory',
 'philippine red cross isabela molecular laboratory',
 'philippine red cross logistics & multipurpose center',
 'philippine red cross passi city molecular laboratory',
 'polymedic medical plaza',
 'president ramon magsaysay provincial hospital genexpert laboratory',
 'prime care alpha covid-19 testing laboratory',
 'primedx laboratories',
 'puerto galera molecular laboratory',
 'puerto princesa city molecular laboratory',
 'qr medical laboratories inc. (vitacare)',
 'qualimed health network - iloilo',
 'qualimed hospital - san jose del monte',
 'qualimed hospital sta. rosa',
 'quezon city molecular diagnostics laboratory',
 'quirino memorial medical center',
 'rhs 7 molecular laboratory (pnp)',
 'rtsd - biÃ±an molecular diagnostic laboratory',
 'rakkk prophet medical center genexpert laboratory',
 'region 1 medical center genexpert laboratory',
 'region 1 medical center rt pcr',
 'region ii trauma and medical center (cartridge-based)',
 'research institute for tropical medicine (ritm)',
 'rizal medical center genexpert laboratory',
 'roxas city diagnostic and laboratory center',
 'roxas memorial provincial hospital molecular laboratory',
 'safeguard dna diagnostic inc. - cebu (rt-pcr)',
 'safeguard dna diagnostics, inc',
 'safeguard dna diagnostics, inc - negros occidental',
 'safegurad dna diagnostics, inc - davao',
 'salvacion oppus yniguez memorial provincial hospital',
 'san antonio city of ilagan hospital',
 'san lazaro hospital (slh)',
 'san miguel foundation testing laboratory',
 'san pablo city general hospital molecular laboratory',
 'san pablo college medical center',
 'san pablo district hospital',
 'siliman university medical center foundation, inc. (cartridge-based pcr)',
 'singapore diagnostics',
 'skyline hospital and medical center cartridge-based pcr',
 'soriano-leyble medical and maternity hospital',
 'sorsogon medical mission group hospital and health services cooperative',
 'south super hi way molecular diagnostic lab',
 'south super highway biomedical laboratories inc.',
 'south super highway biomedical laboratories inc. - cartridge',
 'southern isabela medical center',
 'southern philippines medical center (spmc)',
 'southern philippines medical center (spmc) - pop-up',
 'southern tagalog regional hospital',
 'st. dominic medical center, inc.',
 'st. elizabeth hospital genexpert laboratory',
 'st. louis molecular diagnostic laboratory',
 "st. luke's medical center - bgc (hb) genexpert laboratory",
 "st. luke's medical center - bgc (slmc-bgc)",
 "st. luke's medical center - quezon city (slmc-qc)",
 "st. luke's medical center - quezon city genexpert laboratory",
 'sta. ana hospital - closed system molecular laboratory (genexpert)',
 'sta. ana hospital - closed system molecular laboratory (rt pcr)',
 'sta. rosa cho genexpert laboratory',
 'stark molecular laboratory inc. - cartridge based',
 'stark molecular laboratory, inc.',
 'supercare medical services, inc.',
 'tabuk city covid-19 rt-pcr testing laboratory',
 'taguig city molecular laboratory',
 'tarlac provincial hospital genexpert laboratory',
 'tarlac provincial hospital molecular laboratory',
 'tayug family hospital',
 'teresita jalandoni provincial hospital',
 'the doctors hospital, inc.',
 "the lord's grace medical and industrial clinic",
 'the medical city (tmc)',
 'the medical city - iloilo',
 'the medical city clark',
 'the medical city south luzon',
 'the meidcal city (tmc) - genexpert laboratory',
 'the premier molecular diagnostics',
 'tomboc-salayog hospital',
 'tondo medical center genexpert laboratory',
 'tropical disease foundation',
 'truehealth diagnostics center corp.',
 'um medical & multitest diagnostic inc., molecular laboratory',
 'up national institutes of health (up-nih)',
 'up philippine genome center',
 'up-pgh molecular laboratory',
 'uph - dr. jose g. tamayo medical center',
 'uplb covid-19 molecular laboratory',
 'university of cebu medical center',
 'university of cebu medical center - cartridge-based',
 'university of cebu medical center - rt-pcr',
 'university of perpetual help dalta medical center, inc.',
 'university of the east ramon magsaysay memorial medical center',
 'uswag iloilo molecular laboratory',
 'valenzuela hope molecular laboratory',
 'veteran memorial medical center',
 'vicente sotto memorial medical center (vsmmc)',
 'victoriano luna - afrims',
 'victoriano luna - afrims genexpert laboratory',
 'vitalab molecular laboratory',
 'west metro medical center genexpert laboratory',
 'western visayas medical center (wvmc)',
 'western visayas state university medical center',
 'zamboanga city medical center  (plate-based)',
 'zamboanga city medical center - da satellite laboratory',
 'zamboanga city medical center genexpert laboratory',
 'zamboanga del norte medical center',
 'zamboanga del sur medical center pcr laboratory',
 'truhealthencoder@gmail.com']

In [94]:
second_list = [facility.lower() for facility in facilities['FACILITY'].dropna().unique()]
second_list

['a star laboratories, inc',
 'ac molecular diagnostic laboratory',
 'adela serra ty memorial medical center',
 'al molecular diagnostic laboratory',
 'allegiant regional care hospital',
 'allied care expert (ace) medical center valenzuela, inc',
 'allied medical and molecular laboratory corp.',
 'amai pakpak medical center',
 'amang rodriguez memorial center',
 'amang rodriguez memorial hospital',
 'antipolo city molecular laboratory',
 'antique bio-molecular laboratory',
 'apex mining co. inc.',
 'army general hospita',
 'asian hospital inc.',
 'bacolod queen of mercy hospital',
 'baguio general hospital and medical center',
 'bataan general hospital',
 'batangas medical center',
 'be safe md, inc.',
 'benguet general hospital',
 'best diagnostic corporation',
 'bicol-south luzon sub national reference laboratory',
 'bicol medical center',
 'bicol region general hospital and geriatric medical center',
 'biopath clinical diagnostic, inc.',
 'bohol containerized pcr laboratory',
 'breeze medical services',
 'brokenshire medical center',
 'brtth covid-19 testing laboratory',
 'bukidnon provincial medical center',
 'bulacan medical center',
 'bureau of quarantine',
 'butuan medical center',
 'cabanatuan city m. v. gallego general hospital',
 'cagayan valley chd tb reference laboratory',
 'cagayan valey medical center molecular laboratory',
 'cagayan valley medical center, inc.',
 'calamba doctors hospital',
 'calamba medical center, inc.',
 'caloocan city north medical center',
 'camiguin general hospital - covid-19 molecular laboratory',
 'camsur diagnostic laboratory',
 'caraga regional hospital',
 'cardinal santos medical center',
 'castro maternity hospital and medical center, inc.',
 'cebu doctors university hospital, inc.',
 'cebu tb reference laboratory',
 "central luzon doctor's hospital, inc.",
 'century pinnacle diagnostic and medical corporation',
 'chinese general hospital and medical center',
 'chong hua hospital',
 'city government of zamboanga molecular testing center for covid-19',
 'city of dasmarinas molecular diagnostic laboratory',
 'city of imus molecular laboratory',
 'ciudad medical zamboanga',
 'community general hospital of san pablo city, inc.',
 'corazon locsin montelibano memorial regional hospital',
 'cotabato regional medical center',
 'culion sanitarium and general hospital',
 'dagupan doctors villaflor memorial hospital',
 'dagupan doctors villaflor memorial hospital, inc.',
 'daniel o. mercado medical center',
 'davao de oro provincial hospital',
 'davao doctors hospital (clinica hilario), inc.',
 'davao international airport molecular laboratory',
 'davao one world diagnostic center incorporated',
 'davao regional medical center',
 'de la salle university medical center',
 'de los santos medical center',
 'democrito o. plaza memorial hospital',
 'detoxicare molecular diagnostics laboratory',
 'detoxicare molecular diagnostics laboratory, inc.',
 'divine word hospital',
 'dr. arturo pingoy medical center',
 'dr. fe del mundo medical center',
 'dr. jorge p. royeca hospital',
 'dr. jose fabella memorial hospital',
 'dr. jose n. rodriguez memorial hospital and sanitarium',
 'dr. jose rizal memorial hospital',
 'dr. pablo o. torre memorial hospital',
 'dr. paulino j. garcia memorial research and medical center',
 'dr. rafael s. tumbokon memorial hospital',
 'east avenue medical center',
 'eastern visayas regional covid-19 testing center',
 'el roi molecular diagnostic laboratory',
 'ermita molecular diagnostic laboratory, inc.',
 'excellab diagnostic center',
 'f. y. manalo medical foundation, inc. (formerly new era hospital)',
 'fatima university medical center antipolo corp.',
 'first cabuyao hospital and medical center, inc.',
 'firstchoice diagnostics inc.',
 'gentrimedical center and hospital, inc.',
 'governor celestino gallares memorial medical center',
 'graman medical and maternity hospital inc molecular laboratory',
 'green city medical center',
 'gregorio t. lluch memorial hospital',
 'health connect diagnostics and clinics inc.',
 'health delivery systems',
 'health metrics, inc.',
 'healthway medical',
 'heartland medical and diagnostic center',
 'hero laboratories',
 'hi-precision',
 'ilocos sur provincial hospital gabriela silang',
 'ilocos training regional medical center',
 'iloilo provincial hospital',
 'interpharma solutions philippines, inc.',
 'intramuros molecular laboratory',
 'iom - manila health centre laboratory',
 'jose b. lingad memorial hospital',
 'jose r. reyes memorial medical center',
 'jt cenica medical health system',
 'jtr bicol molecular diagnostic laboratory',
 'kairos diagnostics laboratory',
 'kaiser medical center inc.',
 'kidapawan city molecular laboratory',
 'laguna city provincial hospital - san pablo city district hospital',
 'laguna holy family hospital, inc - satellite molecular laboratory',
 'laguna holy family hospital, inc.',
 'lanao del norte covid-19 testing laboratory',
 'las pinas general hospital and satellite trauma center',
 'lifecore biointegrative inc.',
 'lipa medix medical center',
 'lorma medical center',
 'los amigos davao laboratory',
 'lucena united doctors hospital and medical center',
 'luis hora memorial regional hospital',
 'lung center of the philippines',
 'm diagnostics philippines, inc.',
 'mabini community hospital',
 'maguindanao provincial hospital',
 'makati medical center (hb)',
 'manila diagnostic center for ofw inc.',
 'manila doctors hospital',
 'manuel j. santos hospital',
 'maria estrella general hospital',
 'maria reyna xavier university hospital, inc.',
 'mariano marcos memorial hospital',
 'marikina molecular diagnostic laboratory',
 'marikina valley medical center',
 'marilao medical and diagnostic clinic, inc.',
 'marinduque provincial hospital',
 'mariveles district hospital',
 'mary mediatrix medical center',
 'mauban municipal health office molecular laboratory',
 'mayor hilarion a. ramiro sr. medical center',
 'medical center manila, inc.',
 'medical center of paranaque, inc.',
 'medical center of taguig city, inc.',
 'medical center paranaque, inc.',
 'metro health specialist hospital',
 'metro iloilo hospital and medical center',
 'metro north medical center and hospital, inc.',
 'misamis occidental rt-pcr laboratory',
 'mlang district hospital',
 'mother teresa of calcutta medical center',
 'mount carmel diocesan general hospital',
 'multi-lifecare foundation molecular laboratory',
 'naga city hospital molecular laboratory',
 'national childrens hospital',
 'national kidney and transplant institute',
 'negros oriental provincial hospital',
 'new world diagnostics inc. premium medical branch',
 'next gen pcr diagnostic laboratory',
 'northern mindanao medical center',
 'northern mindanao medical center - satellite covid-19 laboratory',
 'notre dame de chartres hospital',
 'occidental mindoro provincial hospital',
 'olayn medical laboratory, inc.',
 'olongapo city molecular diagnostic laboratory',
 'oriental mindoro provincial hospital',
 "ospa - farmers' medical center",
 'ospital ng lipa',
 'ospital ng muntinlupa',
 'ospital ng palawan',
 'ospital ng paranaque district ii',
 'our lady of mt. carmel medical center molecular laboratory',
 'pampanga medical specialist hospital',
 'pampanga molecular laboratory',
 'pampanga premier medical center',
 'pangasinan molecular diagnostic laboratory',
 'parkway medical and diagnostic center',
 "pasig city children's hospital - child's hope",
 'pasig doctors medical center, inc.',
 'pcr med molecular laboratory',
 'perpetual succour hospital of cebu, inc.',
 'philippine medical diagnostic and laboratory center corporation',
 "philippine children's medical center",
 'philippine general hospital',
 'philippine genome center up-diliman ',
 'philippine heart center',
 'philippine national police crime laboratory',
 'philippine red cross - cagayan de oro chapter',
 'philippine red cross - molecular biology laboratory',
 'philippine red cross - national blood center',
 'philippine red cross - port area',
 'philippine red cross - subic molecular laboratory',
 'philippine red cross clark molecular laboratory',
 'philippine red cross isabela molecular laboratory',
 'pho - molecular biology laboratory',
 'pnp general hospital',
 'polymedic medical plaza',
 'prc - negros occidental molecular laboratory',
 'prc - batangas chapter molecular laboratory',
 'president ramon magsaysay provincial hospital',
 'prime care alpha covid-19 testing laboratory',
 'primedx laboratories',
 'pro 11 rt-pct molecular laboratory',
 'psg station hospital molecular laboratory',
 'puerto galera molecular laboratory (formerly best care medical clinic and diagnostic center, inc.)',
 'puerto princesa city molecular laboratory',
 'qr medical laboratories inc. (vitacare)',
 'qualimed health network - iloilo',
 'qualimed hospital - san jose del monte',
 'qualimed hospital sta. rosa',
 'quezon city molecular diagnostics laboratory',
 'quirino memorial medical center',
 'rakkk prophet medical center, inc.',
 'region 1 medical center',
 'research institute for tropical medicine, inc. (ritm)',
 'rhs 7 molecular laboratory (pnp)',
 'rizal medical center',
 'roxas city diagnostic and laboratory center',
 'roxas memorial provincial hospital molecular laboratory',
 'rtsd - binan molecular diagnostics laboratory',
 'safeguard dna diagnostics, inc.',
 'salvacion oppus yniquez memorial provincial hospital',
 'san antonio city of ilagan hospital',
 'san lazaro hospital (slh)',
 'san miguel foundation testing laboratory',
 'san pablo college medical center',
 "seamen's hospital",
 'siliman university medical center foundation, inc.',
 'singapore diagnostics, inc.',
 'skyline hospital and medical center',
 'soriano - leyble medical and maternity hospital',
 'sorsogon medical mission group hospital and health services cooperative',
 'south super hi way molecular diagnostic lab',
 'south super highway biomedical laboratories inc.',
 'southern isabela medical center',
 'southern philippines medical center (spmc)',
 'southern philippines medical center (spmc) - pop-up',
 'st. dominic medical center, inc.',
 'st. elizabeth hospital',
 'st. louis molecular diagnostic laboratory',
 "st. luke's medical center - bgc (hb)",
 "st. luke's medical center - qc",
 'sta. ana hospital',
 'sta. rosa cho',
 'stark molecular laboratory, inc.',
 'supercare medical services, inc.',
 'tabuk city covid-19 rt-pcr testing laboratory',
 'taguig city molecular laboratory',
 'tarlac provincial hospital',
 'tayug family hospital',
 'teresita jalandoni provincial hospital',
 'the doctors hospital, inc.',
 "the lord's grace medical and industrial clinic",
 'the medical city - iloilo',
 'the medical city - ortigas',
 'the medical city clark, inc.',
 'the medical city south luzon',
 'tomboc-salayog hospital',
 'tondo medical center',
 'tropical diseases foundation',
 'truhealth diagnostics center corp.',
 'um medical and multitest diagnostic inc., molecular laboratory',
 'university of cebu medical center',
 'university of perpetual help system dalta',
 'university of the east ramon magsaysay memorial medical center',
 'up - philippine general hospital',
 'uph - dr. jose g. tamayo medical center',
 'uplb covid-19 molecular laboratory',
 'uswag iloilo molecular laboratory',
 'valenzuela hope molecular laboratory',
 'veteran memorial medical center',
 'vicente sotto memorial medical center (vsmmc)',
 'victoriano luna medical center - afrims - collaborative molecular laboratory',
 'vitalab molecular laboratory',
 'west metro medical center',
 'western visayas medical center (wvmc)',
 'western visayas state university medical center',
 'zamboanga city medical center - ntp culture laboratory',
 'zamboanga del norte medical center',
 'zamboanga del sur medical center']

Symmetric Difference
See: https://www.scaler.com/topics/python-difference-between-two-lists/

In [95]:
difference_result = set(first_list).symmetric_difference(set(second_list))
list_difference_result = list(difference_result)

print(list_difference_result)

['dr. fe del mundo medical center', 'm diagnostics philippines, inc. - pasay (cartridge)', 'next gen pcr diagnostic laboratory - cebu', 'mariano marcos memorial hospital (rt pcr)', 'maguindanao provincial hospital - rt-pcr', 'the medical city clark', 'makati medical center (hb)', 'northern mindanao medical center', 'bataan general hospital', 'greencity medical center', 'cagayan valley medical center, inc.', 'health metrics', 'research institute for tropical medicine, inc. (ritm)', 'university of perpetual help dalta medical center, inc.', 'cagayan valley medical center molecular laboratory - cartridge-based', 'laguna holy family hospital, inc. - satellite molecular laboratory', 'ospital ng paraÃ±aque district ii', 'metro north medical center and hospital inc.', 'jose b. lingad memorial hospital', 'um medical & multitest diagnostic inc., molecular laboratory', 'dr. jose fabella memorial hospital', 'cabanatuan city m. v. gallego general hospital', 'northern mindanao tb regional center', 'cagayan valley chd tb reference laboratory', 'safeguard dna diagnostics, inc - negros occidental', 'allied care expert - valenzuela', 'st. elizabeth hospital', 'philippine genome center up-diliman ', 'region ii trauma and medical center (cartridge-based)', 'pro 11 rt-pct molecular laboratory', 'ospital ng palawan genexpert laboratory', 'amai pakpak medical center', 'truhealth diagnostics center corp.', 'sta. ana hospital - closed system molecular laboratory (genexpert)', 'kairos diagnostics laboratory rt-pcr (2)', 'butuan medical center genexpert laboratory', 'eastern visayas regional covid testing center', 'allegiant regional care hospital - cartridge based', 'hi-precision diagnostics (qc)', 'jtr bicol molecular diagnostic laboratory', 'philippine medical diagnostic & laboratory center corporation', 'west metro medical center genexpert laboratory', 'zamboanga del sur medical center', 'cardinal santos medical center cartridge-based pcr', 'cagayan valley chd genexpert laboratory', 'skyline hospital and medical center cartridge-based pcr', 'detoxicare molecular diagnostics laboratory (2)', 'amai pakpak medical center molecular laboratory', 'lipa medix medical center', 'philippine red cross - cebu chapter', 'bulacan medical center (rt pcr)', 'zamboanga del sur medical center pcr laboratory', 'tarlac provincial hospital genexpert laboratory', 'dagupan doctors villaflor memorial hospital - cartridge based', 'rizal medical center', 'be safe md, inc. - cartridge based', 'de la salle medical and health sciences institute', 'lung center of the philippines (lcp)', 'al molecular diagnostic laboratory - genexpert', 'safeguard dna diagnostics, inc', 'lorma medical center - cartridge based', "national children's hospital (cartridge-based pcr)", 'cotabato regional and medical center rt pcr', 'south super highway biomedical laboratories inc. - cartridge', 'bureau of quarantine', 'caraga regional hospital', 'culion sanitarium and general hospital', 'zamboanga city medical center - ntp culture laboratory', 'up national institutes of health (up-nih)', "st. luke's medical center - qc", 'bulacan medical center genexpert laboratory', 'up philippine genome center', 'm diagnostics philippines, inc. - pasay (rt-pcr)', 'detoxicare molecular diagnostics laboratory - cartridge-based pcr', 'the medical city (tmc)', 'philippine general hospital', 'calamba medical center', 'maguindanao provincial hospital - cartridge based', 'new world diagnostics inc. premium medical branch', 'allied care expert (ace) medical center valenzuela, inc', 'brtth covid-19 testing laboratory', 'gentrimedical center and hospital, inc.', 'st. elizabeth hospital genexpert laboratory', "amosup seamen's hospital", 'medical center paraÃ±aque, inc.', 'makati life medical center', 'president ramon magsaysay provincial hospital', 'sta. rosa cho', 'zamboanga city medical center - da satellite laboratory', 'biopath clinical diagnostics, inc. genexpert laboratory', 'batangas medical center rt pcr laboratory', 'soriano-leyble medical and maternity hospital', 'army general hospita', 'philippine heart center', 'victoriano luna medical center - afrims - collaborative molecular laboratory', 'university of cebu medical center - rt-pcr', 'dr. jose n. rodriguez memorial hospital and sanitarium (tala) rt pcr', 'philippine airport diagnostic laboratory (cartridge-based pcr)', 'philippine red cross cotabato city - maguindanao molecular laboratory', 'ilocos training regional medical center genexpert laboratory', 'amang rodriguez memorial hospital', 'up-pgh molecular laboratory', 'medical center of paranaque, inc. - cartriged based', 'dr. jose fabella memorial hospital - cartridge-based pcr', 'jose b. lingad memorial general hospital - genexpert laboratory', 'northern mindanao medical center rt-pcr laboratory', 'mayor hilarion a. ramiro sr. medical center - cartridge based', 'marikina molecular diagnostics laboratory (mmdl)', 'safeguard dna diagnostic inc. - cebu (rt-pcr)', 'pampanga medical specialist hospital', 'dr. jose n. rodriguez memorial hospital and sanitarium', 'f.y manalo medical foundation, inc. (formerly new era hospital)', 'culion sanitarium and general hospital genexpert laboratory', 'philippine national police crime laboratory', 'oriental mindoro provincial hospital - rtpcr', 'tropical disease foundation', 'biopath clinical diagnostics, inc. - afrims genexpert laboratory', 'amang rodriguez memoral medical center (rt pcr)', 'jose r. reyes memorial medical center', 'marikina molecular diagnostic laboratory', 'asian hospital inc.', "pasig city children's hospital - child's hope", 'de la salle university medical center', 'lipa medix medical center - cartridge-based pcr', 'datu halun sakilan memorial hospital (cartridge-based)', 'philippine red cross (prc)', 'tropical diseases foundation', 'marilao medical and diagnostic clinic, inc. - dagupan city', 'mariveles district hospital genexpert laboratory', 'cabanatuan city m.v. gallego general hospital', 'lung center of the philippines genexpert laboratory', 'philippine airport diagnostic laboratory', 'metro north medical center and hospital, inc.', 'laguna holy family hospital, inc - satellite molecular laboratory', 'el roi molecular diagnostic laboratory (cartridge-based pcr)', 'iom - manila health centre laboratory', 'marilao medical and diagnostic clinc, inc.', 'davao doctors hospital cartridge - based pcr', 'salvacion oppus yniguez memorial provincial hospital', 'pampanga medical specialist hospital - cartridge-based pcr', 'bicol medical center genexpert laboratory', 'biopath clinical diagnostics, inc. (e. rodriguez)', 'research institute for tropical medicine (ritm)', "st. luke's medical center - quezon city genexpert laboratory", 'cotabato regional and medical center genexpert laboratory', 'region 1 medical center rt pcr', 'manila doctors hospital - rt-pcr', 'butuan medical center', 'jose r. reyes memorial medical center genexpert laboratory', 'bicol-south luzon sub national reference laboratory', 'las pinas general hospital and satellite trauma center genexpert laboratory', 'bicol medical center', 'tarlac provincial hospital', 'cebu tb reference laboratory', 'truhealthencoder@gmail.com', "st. luke's medical center - quezon city (slmc-qc)", 'ilocos training regional medical center', 'brtth covid-19 testing laboratoy', 'ilocos training and regional medical center', 'detoxicare molecular diagnostics laboratory, inc.', "seamen's hospital", 'biopath clinical diagnostics, inc. (e. rodriguez) genexpert laboratory', 'puerto galera molecular laboratory', 'eastern visayas regional covid-19 testing center', 'philippine medical diagnostic and laboratory center corporation', 'metro pangasinan molecular laboratory', 'gentrimed molecular laboratory', 'pasig city molecular laboratory', 'biopath clinical diagnostics, inc. - afrims', 'oriental mindoro provincial hospital', 'university of perpetual help system dalta', 'bureau of quarantine - cartridge-based pcr', 'makati medical center (mmc)', 'the meidcal city (tmc) - genexpert laboratory', 'f. y. manalo medical foundation, inc. (formerly new era hospital)', 'next gen pcr diagnostic laboratory - nueva ecija', 'new world diagnostic premium medical branch - genexpert laboratory', 'san pablo city general hospital molecular laboratory', 'maria reyna xavier university hospital, inc.', 'president ramon magsaysay provincial hospital genexpert laboratory', "central luzon doctor's hospital, inc.", 'laguna city provincial hospital - san pablo city district hospital', 'pro 11 rt-pcr molecular laboratory', 'dr. arturo pingoy medical center', 'batangas medical center genexpert laboratory', 'hi-precision', 'philippine red cross - surigao del norte molecular laboratory', 'calamba medical center, inc.', 'zamboanga city medical center  (plate-based)', 'northern mindanao medical center genexpert laboratory', 'cebu tb reference laboratory - molecular facility for covid-19 testing', 'philippine red cross - port area rt-pcr', 'butuan medical center (rt pcr)', 'cotabato regional medical center', 'dr. arturo pingoy medical center genexpert laboratory', 'oriental mindoro provincial hospital genexpert laboratory', 'sta. rosa cho genexpert laboratory', 'east avenue medical center - cartridge based', 'bataan general hospital and medical center genexpert laboratory', 'region 1 medical center genexpert laboratory', 'philippine red cross logistics & multipurpose center', 'city government of zamboanga molecular testing center for covid-19', 'singapore diagnostics, inc.', "st. luke's medical center - bgc (slmc-bgc)", 'philippine general hospital genexpert laboratory', 'kairos diagnostics laboratory cartridge-based pcr', 'rakkk prophet medical center genexpert laboratory', 'chinese general hospital - genexpert laboratory', 'victoriano luna - afrims genexpert laboratory', 'graman medical and maternity hospital inc molecular laboratory', 'a star laboratories', 'northern mindanao medical center - satellite covid-19 laboratory', 'ateneo molecular pathology laboratory', 'amang rodriguez memorial center genexpert laboratory', 'bataan general hospital (rt pcr)', 'batangas medical center', 'marilao medical and diagnostic clinic, inc.', 'truehealth diagnostics center corp.', 'manila healthtek inc.', 'lung center of the philippines', 'biopath clinical diagnostics, inc - cebu', 'safegurad dna diagnostics, inc - davao', 'medical center of paranaque, inc.', 'west metro medical center', 'cebu tb reference laboratory - genexpert', 'graman medical & maternity hospital inc molecular laboratory - cartridge based', 'san pablo district hospital', "st. luke's medical center - bgc (hb)", 'occidental mindoro provincial hospital genexpert laboratory', 'the premier molecular diagnostics', 'mother teresa of calcutta medical center cartridge-based', 'sta. ana hospital - closed system molecular laboratory (rt pcr)', 'cebu doctors university hospital, inc. cartridge-based pcr', 'prc- batangas chapter molecular laboratory', 'philippine heart center genexpert laboratory', 'cagayan valley medical center molecular laboratory', 'tondo medical center genexpert laboratory', 'chong hua hospital cartridge-based pcr laboratory', 'region 1 medical center', 'city of imus molecular laboratory', 'victoriano luna - afrims', 'tarlac provincial hospital molecular laboratory', 'davao international airport molecular laboratory', 'zamboanga city medical center genexpert laboratory', 'iom - manila health centre laboratory - genexpert', 'university of cebu medical center - cartridge-based', 'ospital ng imus', 'soriano - leyble medical and maternity hospital', 'first aide diagnostic center', 'green city medical center', 'national childrens hospital', 'asian hospital and medical center - cartridge', 'graman medical & maternity hospital molecular laboratory', 'asian hospital and medical center', 'dr. jose fabella memorial hospital - rt pcr', 'a star laboratories, inc', 'brokenshire integrated health ministries, inc.', 'asian hospital and medical center - rt-pcr', 'rtsd - binan molecular diagnostics laboratory', 'davao regional medical center genexpert laboratory', "st. luke's medical center - bgc (hb) genexpert laboratory", 'dagupan doctors villaflor memorial hospital, inc.', 'salvacion oppus yniquez memorial provincial hospital', 'olayn medical laboratory, inc. - genexpert laboratory', 'gentrimed cartridge-based pcr laboratory', 'hi-precision diagnostics cartridge-based pcr laboratory (qc)', 'siliman university medical center foundation, inc.', 'pnp crime laboratory', 'ospital ng palawan', 'stark molecular laboratory inc. - cartridge based', 'kairos diagnostics laboratory rt-pcr (1)', 'rizal medical center genexpert laboratory', 'national kidney and transplant institute genexpert laboratory', 'the medical city clark, inc.', 'philippine red cross - national blood center', 'chinese general hospital and medical center', 'mabini community hospital', 'jtrbicol molecular diagnostic laboratory', 'caraga regional hospital genexpert laboratory', 'davao international airport laboratory', 'puerto galera molecular laboratory (formerly best care medical clinic and diagnostic center, inc.)', 'the medical city - ortigas', 'mabini community hospital cartridge-based pcr laboratory', 'iloilo mission hospital molecular biology laboratory', 'safeguard dna diagnostics, inc.', 'um medical and multitest diagnostic inc., molecular laboratory', 'skyline hospital and medical center', 'detoxicare molecular diagnostics laboratory (1)', 'medical center paranaque, inc.', 'amai pakpak medical center genexpert laboratory', 'fe del mundo medical center', 'mariano marcos memorial hospital', 'perpetual succour hospital of cebu, inc. - genexpert laboratory', 'philippine red cross - logistics and training center', 'mariano marcos memorial hospital genexpert laboratory', 'biopath clinical diagnostics, inc - cebu genexpert laboratory', 'bicol regional diagnostic and reference laboratory (brdrl)', 'singapore diagnostics', 'next gen pcr diagnostic laboratory - cartridge-based pcr', 'philippine red cross - subic molecular laboratory', 'prc - batangas chapter molecular laboratory', 'army general hospital molecular laboratory', 'rakkk prophet medical center, inc.', 'philippine red cross - port area - cartridge based', 'up - philippine general hospital', 'amang rodriguez memorial center', 'rtsd - biÃ±an molecular diagnostic laboratory', 'davao doctors hospital (clinica hilario), inc.', 'tondo medical center', 'ospital ng paranaque district ii', 'dr. jose n. rodriguez memorial hospital and sanitarium (tala) genexpert laboratory', "central luzon doctor's hospital genexpert laboratory", 'southern tagalog regional hospital', 'manila doctors hospital - cartridge-based', 'occidental mindoro provincial hospital', 'siliman university medical center foundation, inc. (cartridge-based pcr)', 'chinese general hospital', 'sta. ana hospital', 'new world diagnostic premium medical branch', 'marilao medical and diagnosc clinic, inc. - pasay city', 'bulacan medical center', 'jose b. lingad memorial general hospital', 'city government of zamboanga molecular testing center', 'davao regional medical center rt pcr', 'davao regional medical center', 'philippine red cross passi city molecular laboratory', 'cagayan valey medical center molecular laboratory', 'brokenshire medical center', 'maria reyna xavier university hospital inc.', 'bicol medical center rt-pcr laboratory', 'health metrics, inc.']

In [96]:
len(list_difference_result)

331

331 is a lot to manually annotate. It might be easier to edit only one file, i.e., the file containing information about the testing facilities.

In [97]:
len(first_list)

387

In [98]:
len(second_list)

286

In [99]:
# Facilities that are listed in the COVID-19 tests performed dataset
# that are not in the COVID-19 testing center dataset.
i = 0
for facility in first_list:
    if facility not in second_list:
        print(i, facility)
        i += 1

0 a star laboratories
1 al molecular diagnostic laboratory - genexpert
2 allegiant regional care hospital - cartridge based
3 allied care expert - valenzuela
4 amai pakpak medical center genexpert laboratory
5 amai pakpak medical center molecular laboratory
6 amang rodriguez memoral medical center (rt pcr)
7 amang rodriguez memorial center genexpert laboratory
8 amosup seamen's hospital
9 army general hospital molecular laboratory
10 asian hospital and medical center
11 asian hospital and medical center - cartridge
12 asian hospital and medical center - rt-pcr
13 ateneo molecular pathology laboratory
14 brtth covid-19 testing laboratoy
15 bataan general hospital (rt pcr)
16 bataan general hospital and medical center genexpert laboratory
17 batangas medical center genexpert laboratory
18 batangas medical center rt pcr laboratory
19 be safe md, inc. - cartridge based
20 bicol medical center genexpert laboratory
21 bicol medical center rt-pcr laboratory
22 bicol regional diagnostic and reference laboratory (brdrl)
23 biopath clinical diagnostics, inc - cebu
24 biopath clinical diagnostics, inc - cebu genexpert laboratory
25 biopath clinical diagnostics, inc. (e. rodriguez)
26 biopath clinical diagnostics, inc. (e. rodriguez) genexpert laboratory
27 biopath clinical diagnostics, inc. - afrims
28 biopath clinical diagnostics, inc. genexpert laboratory
29 biopath clinical diagnostics, inc. - afrims genexpert laboratory
30 brokenshire integrated health ministries, inc.
31 bulacan medical center (rt pcr)
32 bulacan medical center genexpert laboratory
33 bureau of quarantine - cartridge-based pcr
34 butuan medical center (rt pcr)
35 butuan medical center genexpert laboratory
36 cabanatuan city m.v. gallego general hospital
37 cagayan valley chd genexpert laboratory
38 cagayan valley medical center molecular laboratory
39 cagayan valley medical center molecular laboratory - cartridge-based
40 calamba medical center
41 caraga regional hospital genexpert laboratory
42 cardinal santos medical center cartridge-based pcr
43 cebu doctors university hospital, inc. cartridge-based pcr
44 cebu tb reference laboratory - genexpert
45 cebu tb reference laboratory - molecular facility for covid-19 testing
46 central luzon doctor's hospital genexpert laboratory
47 chinese general hospital
48 chinese general hospital - genexpert laboratory
49 chong hua hospital cartridge-based pcr laboratory
50 city government of zamboanga molecular testing center
51 cotabato regional and medical center genexpert laboratory
52 cotabato regional and medical center rt pcr
53 culion sanitarium and general hospital genexpert laboratory
54 dagupan doctors villaflor memorial hospital - cartridge based
55 datu halun sakilan memorial hospital (cartridge-based)
56 davao doctors hospital cartridge - based pcr
57 davao international airport laboratory
58 davao regional medical center genexpert laboratory
59 davao regional medical center rt pcr
60 de la salle medical and health sciences institute
61 detoxicare molecular diagnostics laboratory (1)
62 detoxicare molecular diagnostics laboratory (2)
63 detoxicare molecular diagnostics laboratory - cartridge-based pcr
64 dr. arturo pingoy medical center genexpert laboratory
65 dr. jose fabella memorial hospital - cartridge-based pcr
66 dr. jose fabella memorial hospital - rt pcr
67 dr. jose n. rodriguez memorial hospital and sanitarium (tala) genexpert laboratory
68 dr. jose n. rodriguez memorial hospital and sanitarium (tala) rt pcr
69 east avenue medical center - cartridge based
70 eastern visayas regional covid testing center
71 el roi molecular diagnostic laboratory (cartridge-based pcr)
72 f.y manalo medical foundation, inc. (formerly new era hospital)
73 fe del mundo medical center
74 first aide diagnostic center
75 gentrimed cartridge-based pcr laboratory
76 gentrimed molecular laboratory
77 graman medical & maternity hospital inc molecular laboratory - cartridge based
78 graman medical & maternity hospital molecular laboratory
79 greencity medical center
80 health metrics
81 hi-precision diagnostics (qc)
82 hi-precision diagnostics cartridge-based pcr laboratory (qc)
83 iom - manila health centre laboratory - genexpert
84 ilocos training regional medical center genexpert laboratory
85 ilocos training and regional medical center
86 iloilo mission hospital molecular biology laboratory
87 jtrbicol molecular diagnostic laboratory
88 jose b. lingad memorial general hospital
89 jose b. lingad memorial general hospital - genexpert laboratory
90 jose r. reyes memorial medical center genexpert laboratory
91 kairos diagnostics laboratory cartridge-based pcr
92 kairos diagnostics laboratory rt-pcr (1)
93 kairos diagnostics laboratory rt-pcr (2)
94 laguna holy family hospital, inc. - satellite molecular laboratory
95 las pinas general hospital and satellite trauma center genexpert laboratory
96 lipa medix medical center - cartridge-based pcr
97 lorma medical center - cartridge based
98 lung center of the philippines (lcp)
99 lung center of the philippines genexpert laboratory
100 m diagnostics philippines, inc. - pasay (cartridge)
101 m diagnostics philippines, inc. - pasay (rt-pcr)
102 mabini community hospital cartridge-based pcr laboratory
103 maguindanao provincial hospital - cartridge based
104 maguindanao provincial hospital - rt-pcr
105 makati life medical center
106 makati medical center (mmc)
107 manila doctors hospital - cartridge-based
108 manila doctors hospital - rt-pcr
109 manila healthtek inc.
110 maria reyna xavier university hospital inc.
111 mariano marcos memorial hospital (rt pcr)
112 mariano marcos memorial hospital genexpert laboratory
113 marikina molecular diagnostics laboratory (mmdl)
114 marilao medical and diagnosc clinic, inc. - pasay city
115 marilao medical and diagnostic clinc, inc.
116 marilao medical and diagnostic clinic, inc. - dagupan city
117 mariveles district hospital genexpert laboratory
118 mayor hilarion a. ramiro sr. medical center - cartridge based
119 medical center paraÃ±aque, inc.
120 medical center of paranaque, inc. - cartriged based
121 metro north medical center and hospital inc.
122 metro pangasinan molecular laboratory
123 mother teresa of calcutta medical center cartridge-based
124 national children's hospital (cartridge-based pcr)
125 national kidney and transplant institute genexpert laboratory
126 new world diagnostic premium medical branch
127 new world diagnostic premium medical branch - genexpert laboratory
128 next gen pcr diagnostic laboratory - cartridge-based pcr
129 next gen pcr diagnostic laboratory - cebu
130 next gen pcr diagnostic laboratory - nueva ecija
131 northern mindanao medical center genexpert laboratory
132 northern mindanao medical center rt-pcr laboratory
133 northern mindanao tb regional center
134 occidental mindoro provincial hospital genexpert laboratory
135 olayn medical laboratory, inc. - genexpert laboratory
136 oriental mindoro provincial hospital - rtpcr
137 oriental mindoro provincial hospital genexpert laboratory
138 ospital ng imus
139 ospital ng palawan genexpert laboratory
140 ospital ng paraÃ±aque district ii
141 pnp crime laboratory
142 prc- batangas chapter molecular laboratory
143 pro 11 rt-pcr molecular laboratory
144 pampanga medical specialist hospital - cartridge-based pcr
145 pasig city molecular laboratory
146 perpetual succour hospital of cebu, inc. - genexpert laboratory
147 philippine airport diagnostic laboratory
148 philippine airport diagnostic laboratory (cartridge-based pcr)
149 philippine general hospital genexpert laboratory
150 philippine heart center genexpert laboratory
151 philippine medical diagnostic & laboratory center corporation
152 philippine red cross (prc)
153 philippine red cross - cebu chapter
154 philippine red cross - logistics and training center
155 philippine red cross - port area - cartridge based
156 philippine red cross - port area rt-pcr
157 philippine red cross - surigao del norte molecular laboratory
158 philippine red cross cotabato city - maguindanao molecular laboratory
159 philippine red cross logistics & multipurpose center
160 philippine red cross passi city molecular laboratory
161 president ramon magsaysay provincial hospital genexpert laboratory
162 puerto galera molecular laboratory
163 rtsd - biÃ±an molecular diagnostic laboratory
164 rakkk prophet medical center genexpert laboratory
165 region 1 medical center genexpert laboratory
166 region 1 medical center rt pcr
167 region ii trauma and medical center (cartridge-based)
168 research institute for tropical medicine (ritm)
169 rizal medical center genexpert laboratory
170 safeguard dna diagnostic inc. - cebu (rt-pcr)
171 safeguard dna diagnostics, inc
172 safeguard dna diagnostics, inc - negros occidental
173 safegurad dna diagnostics, inc - davao
174 salvacion oppus yniguez memorial provincial hospital
175 san pablo city general hospital molecular laboratory
176 san pablo district hospital
177 siliman university medical center foundation, inc. (cartridge-based pcr)
178 singapore diagnostics
179 skyline hospital and medical center cartridge-based pcr
180 soriano-leyble medical and maternity hospital
181 south super highway biomedical laboratories inc. - cartridge
182 southern tagalog regional hospital
183 st. elizabeth hospital genexpert laboratory
184 st. luke's medical center - bgc (hb) genexpert laboratory
185 st. luke's medical center - bgc (slmc-bgc)
186 st. luke's medical center - quezon city (slmc-qc)
187 st. luke's medical center - quezon city genexpert laboratory
188 sta. ana hospital - closed system molecular laboratory (genexpert)
189 sta. ana hospital - closed system molecular laboratory (rt pcr)
190 sta. rosa cho genexpert laboratory
191 stark molecular laboratory inc. - cartridge based
192 tarlac provincial hospital genexpert laboratory
193 tarlac provincial hospital molecular laboratory
194 the medical city (tmc)
195 the medical city clark
196 the meidcal city (tmc) - genexpert laboratory
197 the premier molecular diagnostics
198 tondo medical center genexpert laboratory
199 tropical disease foundation
200 truehealth diagnostics center corp.
201 um medical & multitest diagnostic inc., molecular laboratory
202 up national institutes of health (up-nih)
203 up philippine genome center
204 up-pgh molecular laboratory
205 university of cebu medical center - cartridge-based
206 university of cebu medical center - rt-pcr
207 university of perpetual help dalta medical center, inc.
208 victoriano luna - afrims
209 victoriano luna - afrims genexpert laboratory
210 west metro medical center genexpert laboratory
211 zamboanga city medical center  (plate-based)
212 zamboanga city medical center - da satellite laboratory
213 zamboanga city medical center genexpert laboratory
214 zamboanga del sur medical center pcr laboratory
215 truhealthencoder@gmail.com

There are 215 such records.

Objective: Manually edit the file to consolidate the records. Add a new column named "EDITED FACILITY NAME"

Rules:
1. Change spelling if there are differences in spelling. 
2. Remove additional words if needed, i.e., "A Star Laboratories, Inc" to "A Start Laboratories" 
3. Add facilities to the list if not included, i.e., Ateneo Molecular Pathology Laboratory

Note:
1. One health facility is not added to the list of facilities, i.e., truhealthencoder@gmail.com. We do not know which province to include this testing facility.

In [100]:
# Edited version of the file (same file as above with additional column)
facilities_2 = "/Users/jimuelcelestejr/Documents/codebook/covid-asmr-philippines/data/COVID-19 Tests/COVID testing facilities (1).xlsx"
facilities_2 = pd.read_excel(facilities_2)

In [101]:
facilities_2

,ID,REGION,PROVINCE,EDITED FACILITY NAME,FACILITY,TYPE,TEST,Remarks
0,1.0,NCR,Metro Manila,a star laboratories,"A Star Laboratories, Inc",Private,rRT PCR,NaN
1,2.0,NCR,Metro Manila,NaN,AC Molecular Diagnostic Laboratory,Private,rRT PCR,NaN
2,3.0,CARAGA,Surigao del Sur,NaN,Adela Serra TY Memorial Medical Center,Government,rRT PCR,NaN
3,4.0,NCR,Metro Manila,NaN,Al Molecular Diagnostic Laboratory,Private,rRT PCR,NaN
4,5.0,NCR,Metro Manila,al molecular diagnostic laboratory - genexpert,Al Molecular Diagnostic Laboratory,Private,Cartridge - Based PCR,NaN
...,...,...,...,...,...,...,...,...
391,348.0,R9,Zamboanga del Sur,zamboanga city medical center genexpert labora...,Zamboanga City Medical Center - NTP Culture La...,Government,Cartridge - Based PCR,NaN
392,NaN,R9,Zamboanga del Sur,zamboanga city medical center (plate-based),NaN,NaN,NaN,NaN
393,NaN,R9,Zamboanga del Sur,zamboanga city medical center - da satellite l...,NaN,NaN,NaN,NaN
394,349.0,R9,Zamboanga del Norte,NaN,Zamboanga del Norte Medical Center,Government,rRT PCR,NaN
395,350.0,R9,Zamboanga del Sur,zamboanga del sur medical center pcr laboratory,Zamboanga del Sur Medical Center,Government,rRT PCR,NaN

In [102]:
facilities_2['Facility_Names_Merged'] = facilities_2['EDITED FACILITY NAME']
facilities_2

,ID,REGION,PROVINCE,EDITED FACILITY NAME,FACILITY,TYPE,TEST,Remarks,Facility_Names_Merged
0,1.0,NCR,Metro Manila,a star laboratories,"A Star Laboratories, Inc",Private,rRT PCR,NaN,a star laboratories
1,2.0,NCR,Metro Manila,NaN,AC Molecular Diagnostic Laboratory,Private,rRT PCR,NaN,NaN
2,3.0,CARAGA,Surigao del Sur,NaN,Adela Serra TY Memorial Medical Center,Government,rRT PCR,NaN,NaN
3,4.0,NCR,Metro Manila,NaN,Al Molecular Diagnostic Laboratory,Private,rRT PCR,NaN,NaN
4,5.0,NCR,Metro Manila,al molecular diagnostic laboratory - genexpert,Al Molecular Diagnostic Laboratory,Private,Cartridge - Based PCR,NaN,al molecular diagnostic laboratory - genexpert
...,...,...,...,...,...,...,...,...,...
391,348.0,R9,Zamboanga del Sur,zamboanga city medical center genexpert labora...,Zamboanga City Medical Center - NTP Culture La...,Government,Cartridge - Based PCR,NaN,zamboanga city medical center genexpert labora...
392,NaN,R9,Zamboanga del Sur,zamboanga city medical center (plate-based),NaN,NaN,NaN,NaN,zamboanga city medical center (plate-based)
393,NaN,R9,Zamboanga del Sur,zamboanga city medical center - da satellite l...,NaN,NaN,NaN,NaN,zamboanga city medical center - da satellite l...
394,349.0,R9,Zamboanga del Norte,NaN,Zamboanga del Norte Medical Center,Government,rRT PCR,NaN,NaN
395,350.0,R9,Zamboanga del Sur,zamboanga del sur medical center pcr laboratory,Zamboanga del Sur Medical Center,Government,rRT PCR,NaN,zamboanga del sur medical center pcr laboratory

In [103]:
index_empty = facilities_2['Facility_Names_Merged'].isna()
facilities_2.loc[index_empty, 'Facility_Names_Merged'] = facilities_2[index_empty]['FACILITY']

In [104]:
facilities_2

,ID,REGION,PROVINCE,EDITED FACILITY NAME,FACILITY,TYPE,TEST,Remarks,Facility_Names_Merged
0,1.0,NCR,Metro Manila,a star laboratories,"A Star Laboratories, Inc",Private,rRT PCR,NaN,a star laboratories
1,2.0,NCR,Metro Manila,NaN,AC Molecular Diagnostic Laboratory,Private,rRT PCR,NaN,AC Molecular Diagnostic Laboratory
2,3.0,CARAGA,Surigao del Sur,NaN,Adela Serra TY Memorial Medical Center,Government,rRT PCR,NaN,Adela Serra TY Memorial Medical Center
3,4.0,NCR,Metro Manila,NaN,Al Molecular Diagnostic Laboratory,Private,rRT PCR,NaN,Al Molecular Diagnostic Laboratory
4,5.0,NCR,Metro Manila,al molecular diagnostic laboratory - genexpert,Al Molecular Diagnostic Laboratory,Private,Cartridge - Based PCR,NaN,al molecular diagnostic laboratory - genexpert
...,...,...,...,...,...,...,...,...,...
391,348.0,R9,Zamboanga del Sur,zamboanga city medical center genexpert labora...,Zamboanga City Medical Center - NTP Culture La...,Government,Cartridge - Based PCR,NaN,zamboanga city medical center genexpert labora...
392,NaN,R9,Zamboanga del Sur,zamboanga city medical center (plate-based),NaN,NaN,NaN,NaN,zamboanga city medical center (plate-based)
393,NaN,R9,Zamboanga del Sur,zamboanga city medical center - da satellite l...,NaN,NaN,NaN,NaN,zamboanga city medical center - da satellite l...
394,349.0,R9,Zamboanga del Norte,NaN,Zamboanga del Norte Medical Center,Government,rRT PCR,NaN,Zamboanga del Norte Medical Center
395,350.0,R9,Zamboanga del Sur,zamboanga del sur medical center pcr laboratory,Zamboanga del Sur Medical Center,Government,rRT PCR,NaN,zamboanga del sur medical center pcr laboratory

In [105]:
output_file = "/Users/jimuelcelestejr/Documents/codebook/covid-asmr-philippines/data/COVID-19 Tests/facilities_2.csv"
facilities_2.to_csv(output_file, index=False)

In [106]:
facility_df = facilities_2[['Facility_Names_Merged', 'PROVINCE']].rename(columns={
    'Facility_Names_Merged': 'Facility', 
    'PROVINCE': 'Province'
})

In [107]:
facility_df['Facility'] = facility_df['Facility'].apply(lambda x: x.lower())
facility_df['Province'] = facility_df['Province'].apply(lambda x: x.upper())

In [108]:
facility_df

                                              Facility             Province
0                                  a star laboratories         METRO MANILA
1                   ac molecular diagnostic laboratory         METRO MANILA
2               adela serra ty memorial medical center      SURIGAO DEL SUR
3                   al molecular diagnostic laboratory         METRO MANILA
4       al molecular diagnostic laboratory - genexpert         METRO MANILA
..                                                 ...                  ...
391  zamboanga city medical center genexpert labora...    ZAMBOANGA DEL SUR
392       zamboanga city medical center  (plate-based)    ZAMBOANGA DEL SUR
393  zamboanga city medical center - da satellite l...    ZAMBOANGA DEL SUR
394                 zamboanga del norte medical center  ZAMBOANGA DEL NORTE
395    zamboanga del sur medical center pcr laboratory    ZAMBOANGA DEL SUR

[396 rows x 2 columns]

In [109]:
output_file = "/Users/jimuelcelestejr/Documents/codebook/covid-asmr-philippines/data/COVID-19 Tests/testing_facilities.csv"
facility_df.to_csv(output_file, index=False)

## COVID-19 Tests Performed per Facility

In [110]:
tests

,facility_name,report_date,avg_turnaround_time,daily_output_samples_tested,daily_output_unique_individuals,daily_output_positive_individuals,daily_output_negative_individuals,daily_output_equivocal,daily_output_invalid,remaining_available_tests,backlogs,cumulative_samples_tested,cumulative_unique_individuals,cumulative_positive_individuals,cumulative_negative_individuals,pct_positive_cumulative,pct_negative_cumulative,validation_status
0,A Star Laboratories,2020-12-08,24.0,15.0,15.0,1.0,14.0,0.0,0.0,8.0,0.0,15,15,1,14,0.07,0.93,NaN
1,A Star Laboratories,2020-12-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
2,A Star Laboratories,2020-12-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
3,A Star Laboratories,2020-12-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
4,A Star Laboratories,2020-12-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393640,truhealthencoder@gmail.com,2023-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393641,truhealthencoder@gmail.com,2023-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393642,truhealthencoder@gmail.com,2023-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393643,truhealthencoder@gmail.com,2023-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393644,truhealthencoder@gmail.com,2024-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN

In [111]:
tests[tests['facility_name']=='A Star Laboratories']

,facility_name,report_date,avg_turnaround_time,daily_output_samples_tested,daily_output_unique_individuals,daily_output_positive_individuals,daily_output_negative_individuals,daily_output_equivocal,daily_output_invalid,remaining_available_tests,backlogs,cumulative_samples_tested,cumulative_unique_individuals,cumulative_positive_individuals,cumulative_negative_individuals,pct_positive_cumulative,pct_negative_cumulative,validation_status
0,A Star Laboratories,2020-12-08,24.0,15.0,15.0,1.0,14.0,0.0,0.0,8.0,0.0,15,15,1,14,0.07,0.93,NaN
1,A Star Laboratories,2020-12-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
2,A Star Laboratories,2020-12-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
3,A Star Laboratories,2020-12-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
4,A Star Laboratories,2020-12-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,A Star Laboratories,2023-12-28,12.0,11.0,11.0,1.0,10.0,0.0,0.0,639.0,0.0,89272,88228,16051,72177,0.18,0.82,NaN
1116,A Star Laboratories,2023-12-29,12.0,7.0,7.0,2.0,5.0,0.0,0.0,630.0,0.0,89279,88235,16053,72182,0.18,0.82,NaN
1117,A Star Laboratories,2023-12-30,12.0,5.0,5.0,2.0,3.0,0.0,0.0,625.0,0.0,89284,88240,16055,72185,0.18,0.82,NaN
1118,A Star Laboratories,2023-12-31,12.0,0.0,0.0,0.0,0.0,0.0,0.0,625.0,0.0,89284,88240,16055,72185,0.18,0.82,NaN
1119,A Star Laboratories,2024-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89284,88240,16055,72185,0.18,0.82,NaN

Filtering out records with report_date > 2023-05-09. The COVID-19 mortality data for this study were collected only until this date.

In [112]:
tests['report_date'] = pd.to_datetime(tests['report_date'])
tests

,facility_name,report_date,avg_turnaround_time,daily_output_samples_tested,daily_output_unique_individuals,daily_output_positive_individuals,daily_output_negative_individuals,daily_output_equivocal,daily_output_invalid,remaining_available_tests,backlogs,cumulative_samples_tested,cumulative_unique_individuals,cumulative_positive_individuals,cumulative_negative_individuals,pct_positive_cumulative,pct_negative_cumulative,validation_status
0,A Star Laboratories,2020-12-08,24.0,15.0,15.0,1.0,14.0,0.0,0.0,8.0,0.0,15,15,1,14,0.07,0.93,NaN
1,A Star Laboratories,2020-12-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
2,A Star Laboratories,2020-12-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
3,A Star Laboratories,2020-12-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
4,A Star Laboratories,2020-12-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393640,truhealthencoder@gmail.com,2023-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393641,truhealthencoder@gmail.com,2023-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393642,truhealthencoder@gmail.com,2023-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393643,truhealthencoder@gmail.com,2023-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393644,truhealthencoder@gmail.com,2024-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN

In [113]:
tests = tests[tests['report_date'] <= pd.to_datetime(' 2023-05-09')]
tests

,facility_name,report_date,avg_turnaround_time,daily_output_samples_tested,daily_output_unique_individuals,daily_output_positive_individuals,daily_output_negative_individuals,daily_output_equivocal,daily_output_invalid,remaining_available_tests,backlogs,cumulative_samples_tested,cumulative_unique_individuals,cumulative_positive_individuals,cumulative_negative_individuals,pct_positive_cumulative,pct_negative_cumulative,validation_status
0,A Star Laboratories,2020-12-08,24.0,15.0,15.0,1.0,14.0,0.0,0.0,8.0,0.0,15,15,1,14,0.07,0.93,NaN
1,A Star Laboratories,2020-12-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
2,A Star Laboratories,2020-12-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
3,A Star Laboratories,2020-12-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
4,A Star Laboratories,2020-12-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15,1,14,0.07,0.93,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393403,truhealthencoder@gmail.com,2023-05-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393404,truhealthencoder@gmail.com,2023-05-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393405,truhealthencoder@gmail.com,2023-05-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393406,truhealthencoder@gmail.com,2023-05-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN
393407,truhealthencoder@gmail.com,2023-05-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12,4,8,0.33,0.67,NaN

Taking the max "cumulative_samples_tested" per facility (group by facility_name).

https://scales.arabpsychology.com/stats/how-to-find-the-max-value-by-group-in-pandas/

In [114]:
tests_df = tests.groupby('facility_name')['cumulative_samples_tested'].max().reset_index()
tests_df

,facility_name,cumulative_samples_tested
0,A Star Laboratories,86372
1,AC Molecular Diagnostic Laboratory,27634
2,AL Molecular Diagnostic Laboratory,235188
3,AL Molecular Diagnostic Laboratory - GeneXpert,7292
4,APEX Mining CO. Inc.,262
...,...,...
380,Zamboanga City Medical Center - DA Satellite L...,98686
381,Zamboanga City Medical Center GeneXpert Labora...,56578
382,Zamboanga del Norte Medical Center,15342
383,Zamboanga del Sur Medical Center PCR Laboratory,44188
384,truhealthencoder@gmail.com,12

In [115]:
tests_df = tests_df.rename(columns={
    'facility_name': 'Facility', 
    'cumulative_samples_tested': 'Cumulative Samples Tested'
})
tests_df

,Facility,Cumulative Samples Tested
0,A Star Laboratories,86372
1,AC Molecular Diagnostic Laboratory,27634
2,AL Molecular Diagnostic Laboratory,235188
3,AL Molecular Diagnostic Laboratory - GeneXpert,7292
4,APEX Mining CO. Inc.,262
...,...,...
380,Zamboanga City Medical Center - DA Satellite L...,98686
381,Zamboanga City Medical Center GeneXpert Labora...,56578
382,Zamboanga del Norte Medical Center,15342
383,Zamboanga del Sur Medical Center PCR Laboratory,44188
384,truhealthencoder@gmail.com,12

In [116]:
tests_df['Facility'] = tests_df['Facility'].apply(lambda x: x.lower())
tests_df

,Facility,Cumulative Samples Tested
0,a star laboratories,86372
1,ac molecular diagnostic laboratory,27634
2,al molecular diagnostic laboratory,235188
3,al molecular diagnostic laboratory - genexpert,7292
4,apex mining co. inc.,262
...,...,...
380,zamboanga city medical center - da satellite l...,98686
381,zamboanga city medical center genexpert labora...,56578
382,zamboanga del norte medical center,15342
383,zamboanga del sur medical center pcr laboratory,44188
384,truhealthencoder@gmail.com,12

In [117]:
output_file = "/Users/jimuelcelestejr/Documents/codebook/covid-asmr-philippines/data/COVID-19 Tests/covid19_tests_performed.csv"
tests_df.to_csv(output_file, index=False)

## Merge 

1. Merge facility_df and test_df
2. Sum up the tests performed by province

In [118]:
facility_df

                                              Facility             Province
0                                  a star laboratories         METRO MANILA
1                   ac molecular diagnostic laboratory         METRO MANILA
2               adela serra ty memorial medical center      SURIGAO DEL SUR
3                   al molecular diagnostic laboratory         METRO MANILA
4       al molecular diagnostic laboratory - genexpert         METRO MANILA
..                                                 ...                  ...
391  zamboanga city medical center genexpert labora...    ZAMBOANGA DEL SUR
392       zamboanga city medical center  (plate-based)    ZAMBOANGA DEL SUR
393  zamboanga city medical center - da satellite l...    ZAMBOANGA DEL SUR
394                 zamboanga del norte medical center  ZAMBOANGA DEL NORTE
395    zamboanga del sur medical center pcr laboratory    ZAMBOANGA DEL SUR

[396 rows x 2 columns]

In [119]:
tests_df

,Facility,Cumulative Samples Tested
0,a star laboratories,86372
1,ac molecular diagnostic laboratory,27634
2,al molecular diagnostic laboratory,235188
3,al molecular diagnostic laboratory - genexpert,7292
4,apex mining co. inc.,262
...,...,...
380,zamboanga city medical center - da satellite l...,98686
381,zamboanga city medical center genexpert labora...,56578
382,zamboanga del norte medical center,15342
383,zamboanga del sur medical center pcr laboratory,44188
384,truhealthencoder@gmail.com,12

In [120]:
i = 0
for facility in tests_df['Facility']:
    if facility not in facility_df['Facility'].values:
        print(i, facility)
        i += 1

0 truhealthencoder@gmail.com

Only records with facility name "truhealthencoder@gmail.com" will not be included.

In [122]:
merged_df = facility_df.merge(tests_df, on='Facility')

In [123]:
merged_df

,Facility,Province,Cumulative Samples Tested
0,a star laboratories,METRO MANILA,86372
1,ac molecular diagnostic laboratory,METRO MANILA,27634
2,adela serra ty memorial medical center,SURIGAO DEL SUR,84410
3,al molecular diagnostic laboratory,METRO MANILA,235188
4,al molecular diagnostic laboratory - genexpert,METRO MANILA,7292
...,...,...,...
381,zamboanga city medical center genexpert labora...,ZAMBOANGA DEL SUR,56578
382,zamboanga city medical center (plate-based),ZAMBOANGA DEL SUR,1765
383,zamboanga city medical center - da satellite l...,ZAMBOANGA DEL SUR,98686
384,zamboanga del norte medical center,ZAMBOANGA DEL NORTE,15342
385,zamboanga del sur medical center pcr laboratory,ZAMBOANGA DEL SUR,44188

In [127]:
merged_df[merged_df['Facility'].isna()]

Empty DataFrame
Columns: [Facility, Province, Cumulative Samples Tested]
Index: []

In [128]:
merged_df[merged_df['Province'].isna()]

Empty DataFrame
Columns: [Facility, Province, Cumulative Samples Tested]
Index: []

In [129]:
merged_df[merged_df['Cumulative Samples Tested'].isna()]

Empty DataFrame
Columns: [Facility, Province, Cumulative Samples Tested]
Index: []

In [130]:
output_file = "/Users/jimuelcelestejr/Documents/codebook/covid-asmr-philippines/data/COVID-19 Tests/covid19_tests_performed_by_facility.csv"
merged_df.to_csv(output_file, index=False)

In [135]:
tests_province_df = merged_df.groupby('Province').sum().reset_index()

/var/folders/ny/jv8cwgpx7ng41dfgnqsvzdnw0000gn/T/ipykernel_23663/889095452.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  tests_province_df = merged_df.groupby('Province').sum().reset_index()

In [137]:
tests_province_df = tests_province_df.rename(columns={'Province': 'PROVINCE'})
tests_province_df

                          PROVINCE  Cumulative Samples Tested
0                   AGUSAN DEL SUR                     144854
1                            AKLAN                      76939
2                            ALBAY                     290687
3                          ANTIQUE                      25303
4                           BATAAN                     291508
5                         BATANGAS                     557066
6                          BENGUET                     936308
7                            BOHOL                     143963
8                         BUKIDNON                      10359
9                          BULACAN                     544194
10                         CAGAYAN                     461277
11                  CAGAYAN DE ORO                     217631
12                          CAINTA                      35033
13                         CALINGA                      19949
14                   CAMARINES SUR                      62175
15                        CAMIGUIN                        439
16                           CAPIZ                      46712
17                          CAVITE                     719926
18                           CEBU                     2096294
19                        COTABATO                     297446
20  COTABATO CITY (NOT A PROVINCE)                       7217
21                    DAVAO DE ORO                      44200
22                 DAVAO DEL NORTE                     167912
23                   DAVAO DEL SUR                    1352364
24                   ILOCOS NORTE                      250855
25                      ILOCOS SUR                       6132
26                          ILOILO                    1122768
27                         ISABELA                     155289
28                        LA UNION                     578394
29                          LAGUNA                     536618
30                 LANAO DEL NORTE                      27754
31                   LANAO DEL SUR                      83750
32                           LEYTE                     510102
33                     MAGUINDANAO                        923
34                      MARINDUQUE                       2305
35                    METRO MANILA                   18963382
36                         MINDORO                      14605
37              MISAMIS OCCIDENTAL                      26391
38                MISAMIS ORIENTAL                     331182
39               MOUNTAIN PROVINCE                      38469
40               NEGROS OCCIDENTAL                     740786
41                 NEGROS ORIENTAL                      53322
42                  NORTH COTABATO                       3950
43                     NUEVA ECIJA                      46905
44                ORIENTAL MINDORO                      29725
45                         PALAWAN                      53745
46                        PAMPANGA                    1199092
47                      PANGASINAN                     242627
48                          QUEZON                     227026
49                           RIZAL                      60117
50                       SORSOGON                       16590
51                  SOUTH COTABATO                     140956
52                  SOUTHERN LEYTE                       2529
53                  SULTAN KUDARAT                      28337
54               SURIGAO DEL NORTE                     181822
55                 SURIGAO DEL SUR                      84410
56                          TARLAC                      80388
57                        ZAMBALES                     231793
58             ZAMBOANGA DEL NORTE                      25898
59               ZAMBOANGA DEL SUR                     475455

In [138]:
output_file = "/Users/jimuelcelestejr/Documents/codebook/covid-asmr-philippines/data/COVID-19 Tests/covid19_tests_performed_by_province.csv"
tests_province_df.to_csv(output_file, index=False)

In [139]:
tests_province_df.shape

(60, 2)

Only 60 provinces have recorded testing facilities.

## COVID-19 Tests Performed per 100,000 population

In [143]:
pop = "/Users/jimuelcelestejr/Documents/codebook/covid-asmr-philippines/data/Philippine Population 2020 by Province and Age Group.xlsx"
pop = pd.read_excel(pop, index_col=0)

In [144]:
pop

,0 to 4,5 to 9,10 to 14,15 to 19,20 to 24,25 to 29,30 to 34,35 to 39,40 to 44,45 to 49,50 to 54,55 to 59,60 to 64,65 to 69,70 to 74,75 to 79,80+
BASILAN,63979,61636,56582,45050,40105,34417,27226,23655,19508,16292,12212,8616,6256,4528,2411,1320,1318
COTABATO CITY (NOT A PROVINCE),38216,35974,34523,35957,36567,32404,24889,20741,17727,13937,10973,7678,5916,3891,2535,1239,1372
LANAO DEL SUR,182925,160576,156233,137554,123810,101418,75871,63633,55861,44624,32651,20800,15346,10967,5999,3125,3114
MAGUINDANAO,223251,193100,179050,138736,124325,106176,89110,76435,66797,50553,34625,22091,15534,10130,5886,3036,2979
SULU,130431,135390,130518,122121,100731,84344,62854,58477,50591,42671,28650,18751,13046,9290,5469,2727,2614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DAVAO ORIENTAL,59339,64443,64640,58727,50134,43254,39477,33234,31758,29504,26855,22762,18565,13140,8676,5220,5256
COTABATO (NORTH COTABATO),133770,145175,141983,129362,111947,103607,93164,80130,72339,63413,55740,44849,36238,25874,16176,9899,9928
SARANGANI,64989,66801,64498,59084,51538,46011,39592,33812,30148,26700,21972,17369,13518,9355,5791,3524,3367
SOUTH COTABATO,176489,180879,175577,161973,157207,144622,129035,109715,100470,85317,72439,57481,44890,31244,19120,11349,10749
SULTAN KUDARAT,94981,98354,95760,91007,81129,70898,62278,52509,46940,40499,34207,26326,20979,14809,9593,5537,5748

In [147]:
pop = pop.sum(axis=1)
pop

BASILAN                            425111
COTABATO CITY (NOT A PROVINCE)     324539
LANAO DEL SUR                     1194507
MAGUINDANAO                       1341814
SULU                               998675
                                   ...
DAVAO ORIENTAL                     574984
COTABATO (NORTH COTABATO)         1273594
SARANGANI                          558069
SOUTH COTABATO                    1668556
SULTAN KUDARAT                     851554
Length: 85, dtype: int64

In [152]:
pop = pop.reset_index().rename(columns={'index': 'PROVINCE', 0: 'Population'})
pop

                          PROVINCE  Population
0                          BASILAN      425111
1   COTABATO CITY (NOT A PROVINCE)      324539
2                    LANAO DEL SUR     1194507
3                      MAGUINDANAO     1341814
4                             SULU      998675
..                             ...         ...
80                  DAVAO ORIENTAL      574984
81       COTABATO (NORTH COTABATO)     1273594
82                       SARANGANI      558069
83                  SOUTH COTABATO     1668556
84                  SULTAN KUDARAT      851554

[85 rows x 2 columns]

In [154]:
pop.merge(tests_province_df, on='PROVINCE')

                          PROVINCE  Population  Cumulative Samples Tested
0   COTABATO CITY (NOT A PROVINCE)      324539                       7217
1                    LANAO DEL SUR     1194507                      83750
2                      MAGUINDANAO     1341814                        923
3                          BENGUET      822619                     936308
4                MOUNTAIN PROVINCE      157798                      38469
5                   AGUSAN DEL SUR      737991                     144854
6                SURIGAO DEL NORTE      531753                     181822
7                  SURIGAO DEL SUR      640512                      84410
8                       ILOCOS SUR      704218                       6132
9                         LA UNION      820343                     578394
10                      PANGASINAN     3159228                     242627
11                         CAGAYAN     1265540                     461277
12                         ISABELA     1695539                     155289
13                          BATAAN      849575                     291508
14                         BULACAN     3696937                     544194
15                     NUEVA ECIJA     2306751                      46905
16                        PAMPANGA     2894309                    1199092
17                          TARLAC     1499064                      80388
18                        ZAMBALES      906184                     231793
19                        BATANGAS     2902855                     557066
20                          CAVITE     4318663                     719926
21                          LAGUNA     3373136                     536618
22                          QUEZON     2223791                     227026
23                           RIZAL     3321325                      60117
24                      MARINDUQUE      238830                       2305
25                ORIENTAL MINDORO      906661                      29725
26                         PALAWAN     1237280                      53745
27             ZAMBOANGA DEL NORTE     1046017                      25898
28               ZAMBOANGA DEL SUR     2017793                     475455
29                           ALBAY     1372550                     290687
30                   CAMARINES SUR     2062277                      62175
31                           AKLAN      612985                      76939
32                         ANTIQUE      611478                      25303
33                           CAPIZ      803879                      46712
34                          ILOILO     2503326                    1122768
35               NEGROS OCCIDENTAL     3216287                     740786
36                           BOHOL     1390524                     143963
37                 NEGROS ORIENTAL     1428548                      53322
38                           LEYTE     2020426                     510102
39                  SOUTHERN LEYTE      428484                       2529
40                        BUKIDNON     1537629                      10359
41                        CAMIGUIN       92696                        439
42                 LANAO DEL NORTE     1083898                      27754
43              MISAMIS OCCIDENTAL      614951                      26391
44                MISAMIS ORIENTAL     1678624                     331182
45                    DAVAO DE ORO      766299                      44200
46                 DAVAO DEL NORTE     1115167                     167912
47                   DAVAO DEL SUR     2450445                    1352364
48                  SOUTH COTABATO     1668556                     140956
49                  SULTAN KUDARAT      851554                      28337

In [156]:
i = 0
for province in pop['PROVINCE']:
    if province not in tests_province_df['PROVINCE'].values:
        print(i, province)
        i += 1

0 BASILAN
1 SULU
2 TAWI-TAWI
3 INTERIM PROVINCE
4 ABRA
5 APAYAO
6 IFUGAO
7 KALINGA
8 AGUSAN DEL NORTE
9 DINAGAT ISLANDS
10 NCR
11 ILOCOS NORTE
12 BATANES
13 NUEVA VIZCAYA
14 QUIRINO
15 AURORA
16 OCCIDENTAL MINDORO
17 ROMBLON
18 CITY OF ISABELA (NOT A PROVINCE)
19 ZAMBOANGA SIBUGAY
20 CAMARINES NORTE
21 CATANDUANES
22 MASBATE
23 SORSOGON
24 GUIMARAS
25 CEBU
26 SIQUIJOR
27 BILIRAN
28 EASTERN SAMAR
29 NORTHERN SAMAR
30 SAMAR (WESTERN SAMAR)
31 DAVAO OCCIDENTAL
32 DAVAO ORIENTAL
33 COTABATO (NORTH COTABATO)
34 SARANGANI

35 provinces do not have testing facility information. Some manual editing is necessary.

1. Check spellings / additional information for each province.

In [158]:
i = 0
for province in tests_province_df['PROVINCE']:
    if province not in pop['PROVINCE'].values:
        print(i, province)
        i += 1

0 CAGAYAN DE ORO
1 CAINTA
2 CALINGA
3 CEBU
4 COTABATO
5 ILOCOS NORTE
6 METRO MANILA
7 MINDORO
8 NORTH COTABATO
9 SORSOGON

10 provinces are in test that are not in the population. It might be a spelling matter. Need some editing.

In [163]:
renaming_map = {
    'CAGAYAN DE ORO': 'MISAMIS ORIENTAL',
    'CAINTA': 'RIZAL',
    'CALINGA': 'KALINGA', 
    'CEBU ': 'CEBU', 
    'COTABATO': 'COTABATO CITY (NOT A PROVINCE)',
    'ILOCOS NORTE ': 'ILOCOS NORTE', 
    'METRO MANILA': 'NCR', 
    'MINDORO': 'ORIENTAL MINDORO',
    'NORTH COTABATO': 'COTABATO (NORTH COTABATO)',
    'SORSOGON ': 'SORSOGON'
}

I am manually editing file ```covid19_tests_performed_by_province.csv``` to reflect the changes as defined here.

Example: Adding Cagayan de Oro to Misamis Oriental and deleting Cagayan de Oro from the list.
See: covid19_tests_performed_by_province_manually_modified.csv

In [169]:
tests_province_df_2 = "/Users/jimuelcelestejr/Documents/codebook/covid-asmr-philippines/data/COVID-19 Tests/covid19_tests_performed_by_province_manually_modified.csv"
tests_province_df_2 = pd.read_csv(tests_province_df_2)

In [170]:
tests_province_df_2

                          PROVINCE  Cumulative Samples Tested
0                   AGUSAN DEL SUR                     144854
1                            AKLAN                      76939
2                            ALBAY                     290687
3                          ANTIQUE                      25303
4                           BATAAN                     291508
5                         BATANGAS                     557066
6                          BENGUET                     936308
7                            BOHOL                     143963
8                         BUKIDNON                      10359
9                          BULACAN                     544194
10                         CAGAYAN                     461277
11                         KALINGA                      19949
12                   CAMARINES SUR                      62175
13                        CAMIGUIN                        439
14                           CAPIZ                      46712
15                          CAVITE                     719926
16                            CEBU                    2096294
17  COTABATO CITY (NOT A PROVINCE)                     304663
18                    DAVAO DE ORO                      44200
19                 DAVAO DEL NORTE                     167912
20                   DAVAO DEL SUR                    1352364
21                    ILOCOS NORTE                     250855
22                      ILOCOS SUR                       6132
23                          ILOILO                    1122768
24                         ISABELA                     155289
25                        LA UNION                     578394
26                          LAGUNA                     536618
27                 LANAO DEL NORTE                      27754
28                   LANAO DEL SUR                      83750
29                           LEYTE                     510102
30                     MAGUINDANAO                        923
31                      MARINDUQUE                       2305
32                             NCR                   18963382
33              MISAMIS OCCIDENTAL                      26391
34                MISAMIS ORIENTAL                     548813
35               MOUNTAIN PROVINCE                      38469
36               NEGROS OCCIDENTAL                     740786
37                 NEGROS ORIENTAL                      53322
38       COTABATO (NORTH COTABATO)                       3950
39                     NUEVA ECIJA                      46905
40                ORIENTAL MINDORO                      44330
41                         PALAWAN                      53745
42                        PAMPANGA                    1199092
43                      PANGASINAN                     242627
44                          QUEZON                     227026
45                           RIZAL                      95150
46                        SORSOGON                      16590
47                  SOUTH COTABATO                     140956
48                  SOUTHERN LEYTE                       2529
49                  SULTAN KUDARAT                      28337
50               SURIGAO DEL NORTE                     181822
51                 SURIGAO DEL SUR                      84410
52                          TARLAC                      80388
53                        ZAMBALES                     231793
54             ZAMBOANGA DEL NORTE                      25898
55               ZAMBOANGA DEL SUR                     475455

In [171]:
i = 0
for province in tests_province_df_2['PROVINCE']:
    if province not in pop['PROVINCE'].values:
        print(i, province)
        i += 1

All provinces in test are renamed accordingly, i.e., reflecting population df.

In [172]:
pop

                          PROVINCE  Population
0                          BASILAN      425111
1   COTABATO CITY (NOT A PROVINCE)      324539
2                    LANAO DEL SUR     1194507
3                      MAGUINDANAO     1341814
4                             SULU      998675
..                             ...         ...
80                  DAVAO ORIENTAL      574984
81       COTABATO (NORTH COTABATO)     1273594
82                       SARANGANI      558069
83                  SOUTH COTABATO     1668556
84                  SULTAN KUDARAT      851554

[85 rows x 2 columns]

In [175]:
province_pop_test_df = pop.merge(tests_province_df_2, on='PROVINCE', how='left')
province_pop_test_df

                          PROVINCE  Population  Cumulative Samples Tested
0                          BASILAN      425111                        NaN
1   COTABATO CITY (NOT A PROVINCE)      324539                   304663.0
2                    LANAO DEL SUR     1194507                    83750.0
3                      MAGUINDANAO     1341814                      923.0
4                             SULU      998675                        NaN
..                             ...         ...                        ...
80                  DAVAO ORIENTAL      574984                        NaN
81       COTABATO (NORTH COTABATO)     1273594                     3950.0
82                       SARANGANI      558069                        NaN
83                  SOUTH COTABATO     1668556                   140956.0
84                  SULTAN KUDARAT      851554                    28337.0

[85 rows x 3 columns]

In [178]:
province_pop_test_df['Cumulative Samples Tested'] = province_pop_test_df['Cumulative Samples Tested'].fillna(0)
province_pop_test_df

                          PROVINCE  Population  Cumulative Samples Tested
0                          BASILAN      425111                        0.0
1   COTABATO CITY (NOT A PROVINCE)      324539                   304663.0
2                    LANAO DEL SUR     1194507                    83750.0
3                      MAGUINDANAO     1341814                      923.0
4                             SULU      998675                        0.0
..                             ...         ...                        ...
80                  DAVAO ORIENTAL      574984                        0.0
81       COTABATO (NORTH COTABATO)     1273594                     3950.0
82                       SARANGANI      558069                        0.0
83                  SOUTH COTABATO     1668556                   140956.0
84                  SULTAN KUDARAT      851554                    28337.0

[85 rows x 3 columns]

In [179]:
province_pop_test_df['Tests / Population'] = province_pop_test_df['Cumulative Samples Tested'] / province_pop_test_df['Population']
province_pop_test_df

,PROVINCE,Population,Cumulative Samples Tested,Tests / Population
0,BASILAN,425111,0.0,0.000000
1,COTABATO CITY (NOT A PROVINCE),324539,304663.0,0.938756
2,LANAO DEL SUR,1194507,83750.0,0.070113
3,MAGUINDANAO,1341814,923.0,0.000688
4,SULU,998675,0.0,0.000000
...,...,...,...,...
80,DAVAO ORIENTAL,574984,0.0,0.000000
81,COTABATO (NORTH COTABATO),1273594,3950.0,0.003101
82,SARANGANI,558069,0.0,0.000000
83,SOUTH COTABATO,1668556,140956.0,0.084478
84,SULTAN KUDARAT,851554,28337.0,0.033277

In [180]:
province_pop_test_df['Tests / Population per 100k (2019-2023)'] = province_pop_test_df['Tests / Population'] * 100000
province_pop_test_df

,PROVINCE,Population,Cumulative Samples Tested,Tests / Population,Tests / Population per 100k (2019-2023)
0,BASILAN,425111,0.0,0.000000,0.000000
1,COTABATO CITY (NOT A PROVINCE),324539,304663.0,0.938756,93875.620496
2,LANAO DEL SUR,1194507,83750.0,0.070113,7011.260713
3,MAGUINDANAO,1341814,923.0,0.000688,68.787477
4,SULU,998675,0.0,0.000000,0.000000
...,...,...,...,...,...
80,DAVAO ORIENTAL,574984,0.0,0.000000,0.000000
81,COTABATO (NORTH COTABATO),1273594,3950.0,0.003101,310.145933
82,SARANGANI,558069,0.0,0.000000,0.000000
83,SOUTH COTABATO,1668556,140956.0,0.084478,8447.783593
84,SULTAN KUDARAT,851554,28337.0,0.033277,3327.680922

In [182]:
output_file = "/Users/jimuelcelestejr/Documents/codebook/covid-asmr-philippines/data/COVID-19 Tests/tests_by_province_per_100k.csv"
province_pop_test_df.to_csv(output_file, index=False)